export const companyInfo = {
  id: 100296,
  name: 'Universitat Spital Zurich',
  logo: null,
  address: 'Wolserstrasse 3',
  plz: 3277,
  ort: 'Obfelden',
  kantone: 8,
  telephone: '342-423-42-34',
  fax: '432-434-34-34',
  category: {
    id: 1,
    name: 'Spital',
    created_at: null,
    updated_at: null,
  },
  companySize: '0-10',
  contactPersonName: 'Filan',
  contactPersonLastName: 'Fisteku',
  contactPersonEmail: 'granit.sejdiu@gmail.com',
  contactPersonGender: '2',
  contactPersonTelephone: '+123 456 789',
  contactPersonFax: '432-434-34-34',
  teamEmail: 'granit.sejdiu@gmail.com',
  page: 'www.google.com',
  shortDescription:
    'VitaMedica personal GmbH ist eine Personal- und Unternehmungsberatung, welche sich auf eine Branche und einen Markt fokussiert hat. Unsere Kunden sind Akutspitäler, Privatkliniken, Alters- und Pflegeheime, kantonale sowie regionale SPITEX-Organisationen, Rehakliniken sowie Ärztezentren in der gesamten Deutschschweiz. Engagierte Beraterinnen vermitteln Stellensuchende an die Kunden und managen den kompetenten Austausch von Informationen. Aktuell suchen wir im Auftrag einer kleinen Langzeitinstitution am rechten Zürichsee-Ufer, für die moderne und helle Abteilung Schwerpunkt Geriatrie / palliativ Care, per sofort oder nach Vereinbarung, eine aufgestellte, humorvolle und führungsstarke Persönlichkeit als Teamleiter/in Pflege 80-100% für eine Festanstellung.',
  created_at: '2019-12-13 21:32:48',
  updated_at: '2020-04-11 13:19:35',
  holidays: '28 Tage',
  maternity_benefits: 'PO',
  benefits: 'Benefits hafjsdhfkasdf\r\nfhkasdjflkasdf',
  company_logo: null,
};
